import type { Region } from '@micah/types';
import React from 'react';
import { Link } from 'react-router-dom';
import { getPmiColor } from '../../utils/pmiColor';
import ShareButton from '../shared/ShareButton';
import RegionCardSkeleton from './RegionCardSkeleton';
// import TagList from '../shared/TagList';

interface RegionCardProps {
    region: Region | null;
    loading?: boolean;
}

const cardClass = "p-6 gap-4 lg:gap-10 col-span-12 grid grid-cols-12 rounded-md bg-bg-dark-primary border border-border-tertiary transition-all duration-300 hover:bg-gradient-to-r hover:from-[#F2F7F9]/20 hover:to-[#97B9C9]/20 relative";
const badgeClass = "py-1 px-2 text-xs font-medium border border-border-tertiary rounded-3xl bg-bg-secondary";

export default function RegionCard({ region, loading = false }: RegionCardProps): React.ReactElement {
    if (loading || !region) {
        return <RegionCardSkeleton />;
    }

    return (
        <Link to={`/region/${region.id}`} className={cardClass}>

            {/* Card body */}
            <div className="col-span-12 lg:col-span-8 flex flex-col gap-6">
                <div className="flex flex-col lg:flex-row items-start lg:items-center gap-5 lg:gap-10 relative">
                    <div className="min-w-16 lg:min-w-[110px] h-16 lg:h-[117px] flex flex-col items-center justify-center rounded-lg relative z-50" style={{ backgroundColor: getPmiColor(region.pmiScore) }}>
                        <h4 className="text-xl lg:text-3xl font-bold">
                            {region.pmiScore != null ? `${region.pmiScore.toFixed(1)}` : 'N/A'}
                        </h4>
                        <p className="text-[10px] lg:text-base font-semibold">PMI Score</p>
                    </div>
                    <div className="flex flex-col">
                        {/* Title + description + tags */}
                        <div className="flex items-center gap-4 mb-3">
                            <h4 className="text-sm lg:text-xl font-semibold text-text-primary">{region.name} Conflict Index</h4>
                            <span className={badgeClass}>Region</span>
                        </div>
                        <p className="text-xs lg:text-base text-text-tertiary  leading-4 lg:leading-6">A prediction market index (PMI) for significant geopolitical or military conflict in {region.name}, generated by collecting all related prediction market contracts, and structuring the data into a PMI with Micah’s AI-native, proprietary software and algorithms.</p>
                        <div onClick={(e) => e.preventDefault()}>
                            {/*<TagList*/}
                            {/*    tags={region.topTags ?? []}*/}
                            {/*    getTagLink={(tag) => `/country/${tag.toLowerCase().replace(/\s+/g, '-')}`}*/}
                            {/*/>*/}
                        </div>
                    </div>
                </div>
            </div>
            <div className="col-span-12 lg:col-span-4">
                <div className="flex flex-row-reverse lg:flex-col items-center lg:items-end h-full justify-between lg:justify-start gap-4">
                    <ShareButton url={`${window.location.origin}/region/${region.id}`} />
                    <div className="flex flex-col lg:flex-row items-center gap-1">
                        <div className="flex items-center">
                            {(region.sourceNames ?? []).slice(0, 4).map((source) => (
                                <img
                                    key={source}
                                    src={`/images/PMMarkets/${source.toLowerCase()}.svg`}
                                    className="-mx-0.5 lg:-mx-1 w-7 h-7 lg:w-auto lg:h-auto object-contain"
                                    alt={source}
                                    onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }}
                                />
                            ))}
                            {(region.sourceNames ?? []).length > 4 && (
                                <span className="rounded-full border border-border-primary w-10 h-10 text-xs leading-3 flex items-center justify-center bg-bg-secondary">
                                +{(region.sourceNames ?? []).length - 4}
                            </span>
                            )}
                            <img src="/images/arrow-right.svg" className="hidden lg:block mx-2" alt="Arrow Right" />
                        </div>
                        <p className="text-base text-text-tertiary font-semibold">
                            {region.activeContractsCount?.toLocaleString() ?? '—'} Contracts
                        </p>
                    </div>
                </div>
            </div>
            <div className="hidden lg:block absolute left-0 top-0 bottom-0 h-full">
                <svg width="75" height="165" viewBox="0 0 75 165" fill="none" xmlns="http://www.w3.org/2000/svg" style={{ color: getPmiColor(region.pmiScore) }}>
                    <g opacity="0.2">
                        <circle cx="2.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="2.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="9.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="16.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="23.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="30.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="37.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="44.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="51.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="58.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="65.5" cy="163.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="2.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="9.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="16.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="23.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="30.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="37.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="44.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="51.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="58.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="65.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="72.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="79.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="86.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="93.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="100.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="107.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="114.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="121.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="128.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="135.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="142.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="149.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="156.5" r="2.5" fill="currentColor"/>
                        <circle cx="72.5" cy="163.5" r="2.5" fill="currentColor"/>
                    </g>
                </svg>
            </div>
        </Link>
    );
}

