import React from 'react';
import Skeleton, { SkeletonTheme } from 'react-loading-skeleton';
import 'react-loading-skeleton/dist/skeleton.css';
import { Link, useParams } from 'react-router-dom';
import HoldingsGridView from '../components/HoldingsGridView';
import HoldingsListView from '../components/HoldingsListView';
import Layout from '../components/Layout';
import PMICardChart from '../components/PMI-score-chart';
import HoldingsControlsBar from '../components/shared/HoldingsControlsBar';
import PmiInfoTooltip from '../components/shared/PmiInfoTooltip';
import { useCountryData } from '../hooks/useCountryData';
import { getPMIcon } from '../utils/getPMIcon';
import { getPmiColor } from '../utils/pmiColor';

function Country(): React.ReactElement | null {
    const { countrySlug } = useParams<{ countrySlug: string }>();

    const { country, loading, notFound, holdingsLoading, holdingsControls } = useCountryData(countrySlug);


    const {
        sortKey,
        setSortKey,
        sortDir,
        setSortDir,
        holdingsFilter,
        setHoldingsFilter,
        holdingsView,
        setHoldingsView,
        handleSort,
        highlightMatch,
        sortedItems: sortedContracts,
    } = holdingsControls;

    if (notFound) {
        return (
            <Layout>
                <div className="py-16 px-12 text-text-secondary">Country not found.</div>
            </Layout>
        );
    }

    const chartData = (country?.trendData ?? []).map(p => ({ month: p.date, value: p.value }));

    return (
        <Layout>
                <div className="p-6 lg:py-16 lg:px-12 border-dashed-spaced relative">
                    {/* Breadcrumb */}
                    <div className="flex items-center gap-2 mb-5 lg:mb-11">
                        {loading ? (
                            <SkeletonTheme baseColor="#C3C3C3" highlightColor="#fff80">
                                <Skeleton width={30} height={14} />
                                <Skeleton width={8} height={14} />
                                <Skeleton width={80} height={14} />
                                <Skeleton width={8} height={14} />
                                <Skeleton width={120} height={14} />
                            </SkeletonTheme>
                        ) : (
                            <div className="">
                                <Link to="/" className="text-sm text-utility-gray font-semibold">World</Link>
                                {country?.regionName && (
                                    <>
                                        <img src="/images/angle-right.svg" alt="Arrow Right" />
                                        <Link to={`/region/${country.regionId}`} className="text-sm text-utility-gray font-semibold">
                                            {country.regionName}
                                        </Link>
                                    </>
                                )}
                                <img src="/images/angle-right.svg" alt="Arrow Right" />
                                <span className="text-sm text-utility-gray font-semibold">{country?.name}</span>
                            </div>
                        )}
                    </div>

                    {/* Title */}
                    <h1 className="text-text-primary font-semibold text-xl lg:text-3xl mb-3">
                        {loading ? <SkeletonTheme baseColor="#C3C3C3" highlightColor="#fff80"><Skeleton width="50%" height={32} /></SkeletonTheme> : country?.name}
                    </h1>
                    <p className="text-sm lg:text-xl text-text-tertiary leading-5 lg:leading-7 font-normal w-full lg:w-[90%]">
                        {loading ? (
                            <SkeletonTheme baseColor="#C3C3C3" highlightColor="#fff80">
                                <Skeleton width="90%" height={14} />
                                <Skeleton width="70%" height={14} style={{ marginTop: 6 }} />
                            </SkeletonTheme>
                        ) : (
                            `A prediction market index (PMI) for significant geopolitical or military conflict in ${country?.name}, generated by collecting all related prediction market contracts, and structuring the data into a PMI with Micah’s AI-native, proprietary software and algorithms.`
                        )}
                    </p>

                    <div className="grid grid-cols-12 gap-5 lg:gap-11 justify-between items-start mt-5 lg:mt-11">
                        {/* Left — stats */}
                        <div className="col-span-12 lg:col-span-3">
                            <div className="grid grid-cols-12 gap-4 mt-5 lg:mt-0 w-full lg:max-w-[367px]">
                                <SkeletonTheme baseColor="#C3C3C3" highlightColor="#fff80">
                                    <div className="col-span-6 lg:col-span-12 lg:col-span-12 flex flex-col text-center p-3 lg:py-8 lg:px-6 rounded-2xl items-start justify-center" style={{ backgroundColor: getPmiColor(country?.pmiScore) }}>
                                        <h4 className="text-xl lg:text-3xl font-bold text-dark-primary">
                                            {loading ? <Skeleton width={80} height={36} baseColor="#9DA1A3" highlightColor="#fff80" /> : (country?.pmiScore !== null && country?.pmiScore !== undefined ? Number(country.pmiScore).toFixed(1) : 'N/A')}
                                        </h4>
                                        <div className="flex items-center gap-1">
                                            <p className="text-xs lg:text-base text-dark-primary font-medium">PMI Score</p>
                                            <PmiInfoTooltip type="pmiScore" />
                                        </div>
                                    </div>
                                    <div className="col-span-6 lg:col-span-12 flex flex-col text-center p-3 lg:py-8 lg:px-6 rounded-2xl bg-bg-secondary items-start justify-center border border-border-tertiary">
                                        <h4 className="text-xl lg:text-3xl font-bold text-text-secondary">
                                            {loading ? <Skeleton width={80} height={36} /> : (country?.activeContractsCount?.toLocaleString() ?? '—')}
                                        </h4>
                                        <p className="text-xs lg:text-base text-text-tertiary font-medium">Contracts</p>
                                    </div>
                                    <div className="col-span-6 lg:col-span-12 flex flex-col text-start lg:text-center p-3 lg:py-8 lg:px-6 rounded-2xl bg-bg-secondary items-start justify-center border border-border-tertiary">
                                        <div className="flex items-center gap-2">
                                            {/*<h4 className="text-3xl font-bold text-text-secondary">*/}
                                            {/*    {loading ? <Skeleton width={40} height={36} /> : (new Set(holdingsContracts.map(c => c.website)).size || '\u2014')}*/}
                                            {/*</h4>*/}
                                            <h4 className="text-xl lg:text-3xl font-bold text-text-secondary">
                                                11
                                            </h4>
                                            <div className="flex items-center">
                                                <img src="/images/PMMarkets/kalshi.svg" className="-mx-0.5 lg:-mx-1 w-4 h-4 lg:w-7.5 lg:h-7.5 object-contain" alt="Icon"/>
                                                <img src="/images/PMMarkets/polymarket.svg" className="-mx-0.5 lg:-mx-1 w-4 h-4 lg:w-7.5 lg:h-7.5 object-contain" alt="Icon"/>
                                                <img src="/images/PMMarkets/robinhood.svg" className="-mx-0.5 lg:-mx-1 w-4 h-4 lg:w-7.5 lg:h-7.5 object-contain" alt="Icon"/>
                                                <img src="/images/PMMarkets/coinbase.svg" className="-mx-0.5 lg:-mx-1 w-4 h-4 lg:w-7.5 lg:h-7.5 object-contain" alt="Icon"/>
                                                {/*{new Set(holdingsContracts.map(c => c.website)).size > 4 && (*/}
                                                {/*    <span className="rounded-full border border-border-primary w-7.5 h-7.5 text-[10px] leading-3 flex items-center justify-center bg-bg-secondary">*/}
                                                {/*    +{new Set(holdingsContracts.map(c => c.website)).size - 4}*/}
                                                {/*</span>*/}
                                                {/*)}*/}
                                                <span className="rounded-full border border-border-primary w-4 h-4 lg:w-7.5 lg:h-7.5 text-[6px] lg:text-[10px] leading-3 flex items-center justify-center bg-bg-secondary">
                                            +7
                                        </span>
                                            </div>
                                        </div>
                                        <p className="text-xs lg:text-base text-text-tertiary font-medium">Prediction Market Exchanges</p>
                                    </div>
                                    <div className="col-span-6 lg:col-span-12 flex flex-col text-center p-3 lg:py-8 lg:px-6 rounded-2xl bg-bg-secondary items-start justify-center border border-border-tertiary">
                                        <h4 className="text-xl lg:text-3xl font-bold text-text-secondary">
                                            {loading ? <Skeleton width={60} height={36} /> : (country?.holdingsCount?.toLocaleString() ?? '—')}
                                        </h4>
                                        <div className="flex items-center gap-1">
                                            <p className="text-xs lg:text-base text-dark-primary font-medium">PMI Holdings</p>
                                            <PmiInfoTooltip type="pmiHoldings" />
                                        </div>
                                    </div>
                                </SkeletonTheme>
                            </div>
                        </div>

                        {/* Right — chart */}
                        <div className="col-span-12 lg:col-span-9 flex flex-col gap-6 items-start">
                            <PMICardChart type="country" data={chartData} loading={chartData.length === 0} />
                        </div>
                    </div>

                    <img src="/images/border-plus.svg" alt="Border Plus" className="absolute -left-[7px] -bottom-2 z-10" />
                    <img src="/images/border-plus.svg" alt="Border Plus" className="absolute -right-[7px] -bottom-2 z-10" />
                </div>
                {/* Component Contracts table */}
                <div className="flex flex-col gap-6 p-6 lg:px-12 border-dashed-spaced relative">
                    <div className="flex flex-col lg:flex-row items-start lg:items-center gap-2 lg:gap-0 justify-between">
                        <h3 className="text-xl font-semibold text-text-primary">PMI Holdings</h3>
                        <HoldingsControlsBar
                            sortKey={sortKey}
                            sortDir={sortDir}
                            onSortChange={(nextKey, nextDir) => {
                                setSortKey(nextKey);
                                setSortDir(nextDir);
                            }}
                            holdingsFilter={holdingsFilter}
                            onHoldingsFilterChange={setHoldingsFilter}
                            holdingsView={holdingsView}
                            onHoldingsViewChange={setHoldingsView}
                            includeRelationship={true}
                        />
                    </div>
                    {holdingsView === 'list' && (
                        <HoldingsListView
                            holdingsLoading={holdingsLoading}
                            sortedContracts={sortedContracts}
                            holdingsFilter={holdingsFilter}
                            sortKey={sortKey}
                            sortDir={sortDir}
                            onSort={handleSort}
                            highlightMatch={highlightMatch}
                            getPMIcon={getPMIcon}
                            showRelationship={true}
                        />
                    )}
                    {holdingsView === 'grid' && (
                        <HoldingsGridView
                            holdingsLoading={holdingsLoading}
                            sortedContracts={sortedContracts}
                            holdingsFilter={holdingsFilter}
                            highlightMatch={highlightMatch}
                            getPMIcon={getPMIcon}
                        />
                    )}
                    <img src="/images/border-plus.svg" alt="Border Plus" className="absolute -left-[7px] -bottom-2 z-10" />
                    <img src="/images/border-plus.svg" alt="Border Plus" className="absolute -right-[7px] -bottom-2 z-10" />
                </div>

        </Layout>
    );
}

export default Country;
