import type { RegionDetail, WorldMarker } from '@micah/types';
import React, { useEffect, useState } from 'react';
import Skeleton, { SkeletonTheme } from 'react-loading-skeleton';
import 'react-loading-skeleton/dist/skeleton.css';
import { Link, useNavigate } from "react-router-dom";
import { hexToRgba } from '../utils/color';
import { getPmiColor } from '../utils/pmiColor';
import PMICardChart from "./PMI-score-chart";
import PmiInfoTooltip from './shared/PmiInfoTooltip';

interface RegionViewProps {
    markers: WorldMarker[];
    activeMarker: WorldMarker | null;
    setActiveMarker: (marker: WorldMarker | null) => void;
    popupRef: React.RefObject<HTMLDivElement | null>;
    selectedRegion: WorldMarker;
    onBack: () => void;
    region: RegionDetail | null;    
}

export default function RegionView({ markers, activeMarker, setActiveMarker, popupRef, selectedRegion, region }: RegionViewProps): React.ReactElement {
    const navigate = useNavigate();
    const [activeView, setActiveView] = useState<'map' | 'graph'>('map');
    const [mapReady, setMapReady] = useState(false);

    useEffect(() => {
        const timer = setTimeout(() => setMapReady(true), 2500);
        return () => clearTimeout(timer);
    }, []);

    const chartData = (region?.trendData ?? []).map(p => ({ month: p.date, value: p.value }));

    const pmiScore = region?.pmiScore != null ? Number(region.pmiScore).toFixed(1) : (selectedRegion.number !== 'N/A' && selectedRegion.number != null ? Number(selectedRegion.number).toFixed(1) : 'N/A');
    const activeContractsCount = region?.activeContractsCount ?? null;

    const regionName = selectedRegion.title.replace(/ Conflict Index$/i, '');

    return (
        <div className="p-6 lg:py-16 lg:px-12 border-dashed-spaced relative">
            {/* Back Button */}
            <div className="flex items-center gap-2 mb-5 lg:mb-11">
                <Link to="/" className="text-sm text-utility-gray font-semibold">World</Link>
                <img src="/images/angle-right.svg" alt="Angle Right"/>
                <span className="text-sm text-text-primary font-semibold">{regionName}</span>
            </div>

            <h1 className="text-text-primary font-semibold text-xl lg:text-3xl mb-3">{regionName}</h1>
            <p className="text-sm lg:text-xl text-text-tertiary leading-5 lg:leading-7 font-normal w-full lg:w-[90%]">A prediction market index (PMI) for significant geopolitical or military conflict in {regionName}, generated by collecting all related prediction market contracts, and structuring the data into a PMI with Micah’s AI-native, proprietary software and algorithms.</p>
            <div className="grid grid-cols-12 gap-5 lg:gap-11 justify-between items-start mt-5 lg:mt-11">
                <div className="col-span-12 lg:col-span-3 order-2 lg:order-1">
                    <div className="grid grid-cols-12 gap-4 mt-5 lg:mt-0 w-full lg:max-w-[367px]">
                        <SkeletonTheme baseColor="#C3C3C3" highlightColor="#fff80">
                        <div className="col-span-6 lg:col-span-12 lg:col-span-12 flex flex-col text-center p-3 lg:py-8 lg:px-6 rounded-2xl items-start justify-center" style={{ backgroundColor: getPmiColor(region?.pmiScore) }}>
                            <h4 className="text-xl lg:text-3xl font-bold text-dark-primary">
                                {region === null ? <Skeleton width={60} height={36} baseColor="#C3C3C3" highlightColor="#fff80" /> : pmiScore}
                            </h4>
                            <div className="flex items-center gap-1">
                                <p className="text-xs lg:text-base text-dark-primary font-medium">PMI Score</p>
                                <PmiInfoTooltip type="pmiScore" />
                            </div>
                        </div>
                        <div className="col-span-6 lg:col-span-12 flex flex-col text-center p-3 lg:py-8 lg:px-6 rounded-2xl items-start justify-center border border-border-tertiary">
                            <h4 className="text-xl lg:text-3xl font-bold text-dark-primary">
                                {region === null ? <Skeleton width={80} height={36} /> : (activeContractsCount != null ? activeContractsCount.toLocaleString() : '—')}
                            </h4>
                            <p className="text-xs lg:text-base text-text-tertiary font-medium">Contracts</p>
                        </div>
                        <div className="col-span-6 lg:col-span-12 flex flex-col text-start lg:text-center p-3 lg:py-8 lg:px-6 rounded-2xl items-start justify-center border border-border-tertiary">
                            <div className="flex items-center gap-2">
                                {/*<h4 className="text-3xl font-bold text-text-secondary">*/}
                                {/*    {region === null ? <Skeleton width={40} height={36} /> : componentExchanges}*/}
                                {/*</h4>*/}
                                <h4 className="text-xl lg:text-3xl font-bold text-dark-primary">
                                    11
                                </h4>
                                <div className="flex items-center">
                                    <img src="/images/PMMarkets/kalshi.svg" className="-mx-0.5 lg:-mx-1 w-4 h-4 lg:w-7.5 lg:h-7.5 object-contain" alt="Icon"/>
                                    <img src="/images/PMMarkets/polymarket.svg" className="-mx-0.5 lg:-mx-1 w-4 h-4 lg:w-7.5 lg:h-7.5 object-contain" alt="Icon"/>
                                    <img src="/images/PMMarkets/robinhood.svg" className="-mx-0.5 lg:-mx-1 w-4 h-4 lg:w-7.5 lg:h-7.5 object-contain" alt="Icon"/>
                                    <img src="/images/PMMarkets/coinbase.svg" className="-mx-0.5 lg:-mx-1 w-4 h-4 lg:w-7.5 lg:h-7.5 object-contain" alt="Icon"/>
                                    {/*{componentExchangesNum != null && componentExchangesNum > 4 && (*/}
                                    {/*    <span className="rounded-full border border-border-primary w-7.5 h-7.5 text-[10px] leading-3 flex items-center justify-center bg-bg-secondary">*/}
                                    {/*        +{componentExchangesNum - 4}*/}
                                    {/*    </span>*/}
                                    {/*)}*/}
                                    <span className="rounded-full border border-border-primary w-4 h-4 lg:w-7.5 lg:h-7.5 text-[6px] lg:text-[10px] leading-3 flex items-center justify-center bg-bg-secondary">
                                            +7
                                    </span>
                                </div>
                            </div>
                            <p className="text-xs lg:text-base text-text-tertiary font-medium">Prediction Market Exchanges</p>
                        </div>
                        <div className="col-span-6 lg:col-span-12 lg:col-span-12 flex flex-col text-center p-3 lg:py-8 lg:px-6 rounded-2xl items-start justify-center border border-border-tertiary">
                            <h4 className="text-xl lg:text-3xl font-bold text-dark-primary">
                                {region === null ? <Skeleton width={60} height={36} /> : (region?.holdingsCount?.toLocaleString() ?? '—')}
                            </h4>
                            <div className="flex items-center gap-1">
                                <p className="text-xs lg:text-base text-dark-primary font-medium">PMI Holdings</p>
                                <PmiInfoTooltip type="pmiHoldings" />
                            </div>
                        </div>
                        </SkeletonTheme>
                    </div>
                </div>
                <div className="col-span-12 lg:col-span-9 flex flex-col gap-6 items-end order-1 lg:order-2 mt-5 lg:mt-0">
                    <div className="flex justify-end items-center border border-border-primary shadow-xs rounded-md overflow-hidden w-full lg:w-auto">
                        <button
                            onClick={() => setActiveView('map')}
                            className={`py-2.5 px-4 border-r border-border-primary cursor-pointer font-semibold flex-1 text-center  lg:flex-auto ${
                                activeView === 'map' ? 'bg-[#414969] text-white' : 'text-bg-primary-alt'
                            }`}
                        >
                            Map
                        </button>
                        <button
                            onClick={() => setActiveView('graph')}
                            className={`py-2.5 cursor-pointer px-4 font-semibold flex-1 text-center  lg:flex-auto ${
                                activeView === 'graph' ? 'bg-[#414969] text-white' : 'text-bg-primary-alt'
                            }`}
                        >
                            14-Day Graph
                        </button>
                    </div>
                    {activeView === 'map' && (
                        <div className="relative animate-fadeIn">
                            <div className="w-full h-full">
                                {!mapReady ? (
                                    <SkeletonTheme baseColor="#1e2a35" highlightColor="#2e3d4d">
                                        <Skeleton width="100%" height={400} borderRadius={12} />
                                    </SkeletonTheme>
                                ) : (
                                    <img src={selectedRegion.mapImage} alt={selectedRegion.title} className="w-full h-full object-contain"/>
                                )}
                            </div>
                            {mapReady && markers.map((marker: WorldMarker) => (
                                <button
                                    key={marker.id}
                                    className="w-1 h-1 md:w-2.5 md:h-2.5 rounded-full absolute animate-pulse-glow cursor-pointer marker-button"
                                    style={{
                                        top: marker.top,
                                        left: marker.left,
                                        backgroundColor: getPmiColor(marker.number !== 'N/A' ? Number(marker.number) : null),
                                        '--glow-color-start': hexToRgba(getPmiColor(marker.number !== 'N/A' ? Number(marker.number) : null), 0.05),
                                        '--glow-color-mid': hexToRgba(getPmiColor(marker.number !== 'N/A' ? Number(marker.number) : null), 0.2),
                                        '--glow-color-end': hexToRgba(getPmiColor(marker.number !== 'N/A' ? Number(marker.number) : null), 0.05),
                                    } as React.CSSProperties}
                                    onClick={() => navigate(`/country/${marker.slug}`)}
                                    onMouseEnter={() => setActiveMarker(marker)}
                                    onMouseLeave={() => setActiveMarker(null)}
                                    aria-label={marker.title}
                                />
                            ))}
                            {mapReady && activeMarker && (
                                <div
                                    ref={popupRef}
                                    className="absolute  z-10 shadow-lg transition-all duration-300 ease-in-out transform opacity-0 animate-popup py-3 px-4 bg-bg-dark-primary rounded-lg border border-black/10 flex flex-col gap-2 items-center justify-center max-w-35 w-full text-center"
                                    style={{
                                        top: `calc(${activeMarker.top} - 12px)`,
                                        left: `calc(${activeMarker.left} + 0px)`,
                                        transform: 'translate(0, -100%)'
                                    }}
                                    onMouseEnter={() => setActiveMarker(activeMarker)}
                                    onMouseLeave={() => setActiveMarker(null)}
                                >
                                    <h2 className="font-semibold text-gray-900 w-16 h-10 rounded-lg flex items-center justify-center text-lg" style={{ backgroundColor: activeMarker.hotspotColor }}>{activeMarker.number != null ? Number(activeMarker.number).toFixed(1) : 'N/A'}</h2>
                                    <h4 className="text-sm text-text-primary font-semibold">{activeMarker.title}</h4>
                                </div>
                            )}
                        </div>
                    )}
                    {activeView === 'graph' && (
                        <div className="w-full animate-fadeIn">
                            <PMICardChart type="region" data={chartData} loading={region === null} />
                        </div>
                    )}
                </div>
            </div>
            <img src="/images/border-plus.svg" alt="Border Plus" className="absolute -left-[7px] -bottom-2 z-10"/>
            <img src="/images/border-plus.svg" alt="Border Plus" className="absolute -right-[7px] -bottom-2 z-10"/>
        </div>
    );
}
